### ISSUE TITLE
Null transactions

### ISSUE THREAD

**Issue by xedsvg** [CoinFabrik/simple-nodejs-blockchain-parser#1]
Parsing blocks with null transactions throws an error.

Looking into it and commenting ` console.dir(parsedTx.toObject());` throws a new error:

``` 
buffer.js:219
length += list[i].length;
                       
TypeError: Cannot read property 'length' of null
    at Function.Buffer.concat (buffer.js:219:24)
    at getRawTx (simple-nodejs-blockchain-parser/blockchain-parser.js:62:17)
    at Object.<anonymous> (simple-nodejs-blockchain-parser/blockchain-parser.js:104:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

 Commenting  `return Buffer.concat(txParts);`

```
blockchain-parser.js:7
var sizeInt = size.readUInt8();

TypeError: Cannot read property 'readUInt8' of null
    at readVarInt (/simple-nodejs-blockchain-parser/blockchain-parser.js:7:23)
    at getRawTx (/simple-nodejs-blockchain-parser/blockchain-parser.js:44:24)
    at Object.<anonymous> (/simple-nodejs-blockchain-parser/blockchain-parser.js:104:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

Any ideas?

**Comment by ferni** [comment]
Hi,

So this repo is kind of abandoned.  Also with segwit incoming there will be a lot of problems that need to be solved. I would recommend that you use something like https://bitcore.io/ for your purposes.
